version: "3"

services:
  laravel:
    build:
      context: ../Laravel
      dockerfile: Dockerfile.prod
    image: matheusblm/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ../Nginx
      dockerfile: Dockerfile
    image: matheusblm/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
networks:
  laranet:
    driver: bridge
